#+TITLE: Digital Collections Page
#+AUTHOR: Matt Teichman
#+DESCRIPTION: DLDC Guide to creating and updating a new digital collections page

#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* Introduction

  This document is intended to help walk DLDC staff through the process of
  creating a new digital collections page.  Currently, the majority of the
  Library's digital collections are on standalone websites created in different
  ways using different frameworks by different people.  The purpose of the
  framework outlined here is to provide a way to fold all those digital
  collections websites into a single, centralized web app---our Wagtail site,
  which is the main library website you see when you go to
  =www.lib.uchicago.edu=.

  The [[guide-section][Guide]] section is intended as a quick walkthrough to get you going bringing
  a new digital collection on board.  The [[reference-section][Reference]] section provides a more
  comprehensive explanation of the various parts of our digital collections
  framework, and is intended to be read on an as-needed basis rather than
  linearly, i.e. if you are wondering how a specific feature works, you can look
  up the section describing that feature.

* Prerequisites

  These instructions assume that you are a UChicago DLDC developer working on
  our =library_website= app, the source for which is located [[https://github.com/uchicago-library/library_website][here]].

* Guide <<guide-section>>

  Suppose that, as a DLDC staff member, you are in possession of a digital
  colleciton that you would like to create a collection page for.  The purpose
  of this guide is to outline the steps necessary to 'onboard' a new digital
  collection.

  So that we have an example to work with, imagine that you have just been asked
  to add a collection of back issues of the classic web comic, /Doctor Fun/, to
  the collection.  You will need to go through the following steps:

  + load all the collection data (i.e. each comic) onto our Mark Logic server
  + load the relevant collection data onto our IIIF and Loris servers (i.e. a
    hi-res image of each comic, along with basic metadata)
  + populate the 'collection' panel in the Wagtail admin interface for that
    collection page
  + give the models and templates for the collection page in Wagtail a once-over
    to see whether any features need to be added

** Mark Logic Preparation

   The first thing to do is populate our Mark Logic database with the collection
   objects (back issues of /Doctor Fun/, in this case), along with all the
   metadata we have for each object.  Metadata for each object would include
   information such as: who created it, when was it created, who is the
   publisher, what geographic regions does it cover (if applicable), etc.

   [[https://www.marklogic.com/][Mark Logic]] is a NoSQL database with key-value lookup and RDF graph
   capabilities.  We are using our Mark Logic database as a 'source of truth'
   for most of our digital collections, with one or two exceptions where that is
   not feasible.  The Mark Logic record for any given object should contain all
   the information that we have about it (and are planning to use).

   If you would like to add a new digital collection to our Mark Logic database,
   please contact [[https://www.lib.uchicago.edu/about/directory/staff/charles-blair/][Charles Blair]] and [[https://www.lib.uchicago.edu/about/directory/staff/john-jung/][John Jung]] for assistance.

** IIIF Preparation

   The second step for onboarding a new collection is to set our IIIF server up.
   The purpose of the IIIF server is to:

   + provide the information the page uses to create its browse listings
   + provide a URL the Universal Viewer app can use to live-display a collection
     object in the collection page

   The IIIF server provides this information in the form of JSON objects,
   following the [[https://iiif.io/api/][IIIF specification]].  The IIIF browses provide groupings of
   collections objects under categories, and provide a link to the IIIF manifest
   for each object.

   If you are tasked with onboarding a new digital collection, please contact
   [[https://www.lib.uchicago.edu/about/directory/staff/john-jung/][John Jung]] for assistance.  The remaining parts of this section will outline
   how the IIIF server should behave, once you are done with that part of the
   process.

*** ARK Identifiers

    Every object in our digital collections is assigned an [[https://n2t.net/e/ark_ids.html][ARK identifier]].  This
    can be thought of as a universal 'primary key' for looking the object up in
    any database that lists it.  ARK identifiers are similar to [[https://www.doi.org/][DOI]]-s, which you
    may have come across while doing scholarly research.  However, one
    disadvantage to using a DOI as the primary identifier for our object is that
    DOI resolution is proprietary, which means that every time you want to look
    an object up by DOI, you need to use the CrossRef website.  We would prefer
    to be able to look objects in our collection up without being beholden to a
    third-party lookup service and whatever baggage comes along with it, in
    terms of performance, service outage, and compatibility-breaking upgrades

    Simplifying somewhat, our ARK identifiers have two parts.  The prefix is
    always =ark:/61001/=.  =61001= is the Name Assigning Authority Number for
    the University of Chicago.  The second part is called the [[https://n2t.net/e/noid.html][NOID]], and it
    consists of an alphanumeric hash that uniquely identifies the object.  (I
    know what you're thinking; please keep your early 80s arcade game puns to
    yourself.)

    For exmaple, the ARK identifier for our [[https://www.lib.uchicago.edu/collex/collections/social-scientists-map-chicago/object/b2s05v615c5v/][Lawndale Community]] map is:

    #+begin_example
      ark:/61001/b2s05v615c5v
    #+end_example

    To look an object up by ARK, you should use the University of Chicago
    Library's ARK resolver API, located at:

    #+begin_example
      https://www.lib.uchicago.edu/ark:/61001/
    #+end_example

    To look the [[https://www.lib.uchicago.edu/collex/collections/social-scientists-map-chicago/object/b2s05v615c5v/][Lawndale Community]] map up in our ARK resolver using its ARK,
    simply append the NOID to the above URL:

    #+begin_example
      https://www.lib.uchicago.edu/ark:/61001/b2s05v615c5v
    #+end_example

    This permanent URL will take you to the webpage for that collection object,
    in perpetuity.  For more information on how our ARK resolver works, please
    see the offical documentation here:

    #+begin_example
      https://dldc.lib.uchicago.edu/local/ldr/ark.html
    #+end_example

*** Routing Scheme

    We use the hostname =iiif-collection.lib.uchicago.edu= in production and the
    hostname =iiif-collection-dev.lib.uchicago.edu= for development.  The
    workflow is to test upgrades/changes to the way the IIIF data are formatted
    on the development server, then move them over to the production server once
    we're convinced they work.  In the examples that follow, we will presume the
    production hostname.

    We use a 'slugified' version of the collection name as the root path for a
    collection's browses in IIIF.  'Slugified' means that all capital letters
    are lowercased and all space characters are changed to hyphens.  For
    instance, if the name of your collection is 'Digital Media Archive', then
    the slugified name should be =digital-media-archive=.

*** IIIF: Browse Type Route

    The routing scheme for a cluster browse type in IIIF is as follows:

    #+begin_example
      https://iiif-collection.lib.uchicago.edu/[NAME OF COLLECTION]/cluster-browse/[NAME OF BROWSE TYPE].json
    #+end_example

    An actual example of such a URL route would be:

    #+begin_example
      https://iiif-collection.lib.uchicago.edu/social-scientists-map-chicago/cluster-browse/decade.json
    #+end_example

    All the browse type routes you set up in IIIF should look like that.

*** IIIF: Browse Route

    The routing scheme for a cluster browse type in IIIF is as follows:

    #+begin_example
      https://iiif-collection.lib.uchicago.edu/[NAME OF COLLECTION]/cluster-browse/[NAME OF BROWSE TYPE]/[NAME OF BROWSE].json
    #+end_example

    An actual example of such a URL route would be:

    #+begin_example
      https://iiif-collection.lib.uchicago.edu/social-scientists-map-chicago/cluster-browse/decade/1930s.json
    #+end_example

    All the browse type routes you set up in IIIF should look like that.

*** IIIF: Object Manifest Route

    The main source of information on a digital collection object in IIIF is the
    manifest.  Object manifests on our IIIF server are not split up by
    collection; they are accessed only by their ARK identifier.

    The hostname, as always, is =iiif-collection.lib.uchicago.edu=.  The route
    for viewing an object manifest is:

    #+begin_example
      https://iiif-collection.lib.uchicago.edu/object/[ARK IDENTIFIER].json
    #+end_example

    So, for instance, the URL for the IIIF manifest for our [[https://www.lib.uchicago.edu/collex/collections/social-scientists-map-chicago/object/b2qd0bb4kk01/][Brighton Park]] map is
    as follows:

    #+begin_example
      https://iiif-collection.lib.uchicago.edu/object/ark:/61001/b2qd0bb4kk01.json
    #+end_example

*** Create IIIF Manifests and Browses

    When you're done, the IIIF server should be serving up browses and manifests
    for your collection at those routes.  For more information on setting that
    up, please get in touch with [[https://www.lib.uchicago.edu/about/directory/staff/john-jung/][John Jung]].

** Create Wagtail Admin Panel

   The third major step in setting your new digital collections page up is to
   populate the relevant Wagtail admin panels for it.  Perhaps the collection
   you're working on already has a page in Wagtail---if so, its =Collection= tab
   will be empty, so all you'll have to do is populate it.  If the collection
   you're working on doesn't already have a page in Wagtail, you'll need to
   create it and populate both the =Content= and =Collection= tabs.

   The purpose of the Wagtail admin panels is to provide for you to enter all
   the information that's specific to the collection you're adding.  This
   information will go into the Wagtail database, and it will generate the
   entire collection site from the information you provided.  That is, it will
   automatically generate list and cluster browses (and, eventually, also facets
   and searches), the landing page for the collection, and object pages for all
   objects in the collection.  From Wagtail's point of view, all of that is one
   single 'page'.  

   To get to the Wagtail admin interface, scroll to the bottom of any webpage on
   the [[https://www.lib.uchicago.edu][main library website]] and click on the link that says =Staff Login=.  This
   will take you to a Shibboleth login page, which will accept your =cnetid= and
   cnet password.  Once you're logged into the admin interface, click on the
   following series of =>= in the main menu, on the left of the screen:

   #+begin_example
     Pages > The University of Chicago Library > Collections & Exhibits > Collections
   #+end_example

   If the Wagtail page for your new collection doesn't yet exist, click on
   =Collections=.  This will take you to a list of all our collection pages.  To
   create a new page for your collection, click on =+ ADD CHILD PAGE= under the
   title =Collections=, in between the =VIEW LIVE= and =MORE= buttons.

   If the Wagtail page for your collection already exists---this will probably
   be the case for the majority of collections we decide to onboard, at least in
   the initial stages---continue clicking through the series of =>= in the menu
   until you get to the name of your collection:

   #+begin_example
     Collections > [NAME OF YOUR COLLECTION]
   #+end_example

   Next, you can begin populating the *Collection* tab.  The *Content* tab
   contains basic information about the collection, which is mainly used to
   provide the content for the collection's landing page and sidebar.  The
   *Collection* tab contains the information that will be used to automatically
   create all the list browses, cluster browses, and object pages (and,
   eventually, also facets and searches).

   Next, we'll run through all the sections of the *Collection* tab, as of
   April 2021.

*** Highlighted Records

    This field in the panel should contain the URL to the browse that will be
    used to display a preview of the first five items in the collection on the
    landing page.  It's like an abbreviated browse that lets the user jump right
    into browsing the collection.

    Currently, we are just using the list browse for this feature; our Wagtail
    model/view automatically truncates it to just show the first five.  So for
    the time being, this should be a link to the IIIF list browse for the
    collection you're working on.

*** Citation Configuration

    The digital collections object page has a menu called 'Cite This', which
    appears below the viewer for the object.  Inside the viewer is a live
    preview of what a citation for the relevant object would look like, and the
    user can toggle between Chicago, APA, and MLA citation styles.  The way we
    construct these citations is fairly complicated and will be described in
    detail in the [[reference-section][Reference]] section of this document.

    This should contain the configuration file for the citation service.  The
    configuration file is in =INI= format.  You shouldn't have too much trouble
    getting started with it, because it is auto-populated by default with a
    minimal reasonable standard configuration.  However, you will have to edit
    it if you want to customize which Mark Logic metadata fields appear in the
    citations for the objects in your new collection.  The configuration file is
    in =INI= format; for full information on how to edit it, please see the
    [[citation-section][Citation Service]] section under [[reference-section][Reference]].

*** Searches
    
    When this feature is fleshed out, we'll use this section to enumerate what
    types of searches the collection will offer.  For instance, maybe we want to
    allow the user to search a collection by author, or by date.

    This feature is not implemented as of April 2021---so this section of the
    admin panel is essentially a placeholder.

*** List Browses

    A list browse is a listing of every object in a collection, paginated in
    increments of 25.  What makes different list browses different is the order
    in which they sort the collection items.  So for example, a date list browse
    might sort the items in ascending order by the date they were released, and
    a title list browse might sort the items in ascending alphabetical order of
    their titles.  But both browses will contain all the items in the
    collection.

    Once you have determined which list browses you would like to make available
    in your new collection, press the =+ ADD LIST BROWSES= button to make a list
    browse object, for each of the browses you are planning to offer.

    Currently, we are only using two of the fields in our list browse objects:
    *Label* and *Link text override*.  *Label* should be a capitalized version
    of the name of the list browse in IIIF.  For instance, if the date list
    browse for a collection is called 'date' in IIIF, then the list browse
    object you create in the Wagtail admin interface should have =Date= for a
    label.

    *Link text override* tells Wagtail how to display the browse when it links
    to it.  For example, the date list browse for the [[https://www.lib.uchicago.edu/collex/collections/social-scientists-map-chicago/][Social Scientists Map
    Chicago]] collection is called 'date' in IIIF---Wagtail needs to know that to
    pull the information about the list browse from IIIF---but the browse
    displays to the reader as 'All Maps by Date'.  *Link text override* is an
    optional field, so if you leave it blank, then the browse will display under
    a capitalized version of its IIIF name.

*** Cluster Browses

    As of April 2021, cluster browses have a different structure from list
    browses.  List browses go 'one level deep', because they only correspond to
    different ways of sorting all items in an entire collection.  However,
    cluster browses break the items in a collection up into subcategories, and
    each collection potentially has different ways we'll want to break it up
    into subcategories.

    A cluster browse type is a way of breaking a collection up into
    subcategories.  A cluster browse is the name we give each of those
    subcategories.  So for instance, the Social Scientists Map Chicago
    collection has a 'subject' cluster browse type and a 'decade' cluster browse
    type.  
    
** The Once Over

* Reference <<reference-section>>

  This section is to-be-written.

** Routing Scheme

** Wagtail Admin Panel

** IIIF Manifests

** IIIF Browses

*** List Browses

*** Cluster Browses

** Landing Page

** Intermediate Pages

*** Cluster Browses

*** List Browses

*** Searches & Facets

** Object Page

*** Citation Service <<citation-section>>

**** Turtle Data

**** Social Media Links

**** LUNA/BTAA links

**** Physical Object

*** Metadata fields

**** Additional Fields: Permanent URL and Parent Collection

*** Universal Viewer

